Fix/gh r musl
zdharma-continuum/zinit pull request #542
Opened 2023-06-16 01:59 UTC by vladdoster

## Description

## Related Issue(s)

Closes #539

## Types of changes 

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] Documentation change
- [ ] New feature (non-breaking change which adds functionality)

## Checklist:

- [X] All new and existing tests passed.
- [ ] I have added tests to cover my changes.
- [ ] I have updated the documentation accordingly.

2023-06-16 06:43 UTC, pschmitt commented on zinit-install.zsh
> +        completions=( "${ZINIT[PLUGINS_DIR]}/${id_as//\//---}"/**/_[^_.]*~*(*.zwc|*.html|*.txt|*.png|*.jpg|*.jpeg|*.js|*.md|*.yml|*.ri|_zsh_highlight*|/zsdoc/*|*.ps1)(DN^/) )
Please rebase. This is from #528 and should stay in!

2023-06-16 06:44 UTC, pschmitt commented on .github/workflows/documentation.yaml
> +          fi
Please rebase. This reverts a bunch of PR that I merged in. This here is #535

2023-06-16 06:45 UTC, pschmitt requested changes
Please rebase.

2023-08-30 04:39 UTC, vladdoster commented
Closed in favor of #564.

2023-08-30 04:39 UTC, closed without merging