Testing!
zdharma-continuum/zinit pull request #96
Opened 2021-11-20 15:03 UTC by pschmitt

2021-11-20 21:03 UTC, pschmitt commented
This needs a follow-up to reach a higher test coverage (#testAllTheIces) but at least the framework is now there 🥳

2021-11-20 21:06 UTC, pschmitt commented
The failing test (plugins) already highlights a currently unsolved issue that materializes when running `@zinit-scheduler-burst` with Ansible or other configuration management tools:

some ices get ignored when run non-interactively 🤷
Will open a separate issue for that.

2021-11-21 07:13 UTC, alichtman requested changes

2021-11-21 07:13 UTC, alichtman commented on doc/HACKING.md
> +1. Install [zunit]()https://zunit.xyz and [revolver](https://github.com/molovo/revolver):
```suggestion
1. Install [zunit](https://zunit.xyz) and [revolver](https://github.com/molovo/revolver):
```

2021-11-21 07:17 UTC, merged

2021-11-21 11:28 UTC, pschmitt commented
The zunit plugin issue is fixed by #99